Test/internal/add config observability unit test
vdaas/vald pull request #1155
Opened 2021-04-07 08:59 UTC by hlts2

### Description:

I added test for `internal/config/observability.go` and godoc comment.
~~grammer check passed~~

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.16
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2021-04-08 09:26 UTC, vankichi approved these changes

2021-04-12 02:25 UTC, kevindiu requested changes
please fix test error.
https://github.com/vdaas/vald/pull/1155/checks?check_run_id=2285891800

2021-04-12 05:09 UTC, kevindiu approved these changes
LGTM

2021-04-13 02:10 UTC, vankichi submitted a review, later dismissed

2021-04-13 03:21 UTC, kevindiu commented
/rebase
/format
/approve

2021-04-13 03:30 UTC, merged