Remove rinx from several yamls
vdaas/vald pull request #1451
Opened 2021-09-27 05:49 UTC by rinx

Signed-off-by: Rintaro Okamura <rintaro.okamura@gmail.com>

### Description:

- Remove me from chatops_permissions.yaml
- Remove me from dependabot.yaml

### Related Issue:

Nothing

### How Has This Been Tested?:

Nothing

### Environment:

- Go Version: 1.17.1
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [X] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [X] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2021-09-28 01:16 UTC, kevindiu submitted a review, later dismissed

2021-09-28 01:18 UTC, kpango requested changes

2021-09-28 01:18 UTC, kpango commented on .github/chatops_permissions.yaml
> -      - author
How about leaving it in the contributor role?

2021-09-28 01:18 UTC, kpango commented on .github/dependabot.yml
> -      - rinx
Can I add kmrmt?

2021-09-28 01:26 UTC, hlts2 reviewed
LGTM
after you add kmrmt account to dependabot.yml, I will approve this PR!

2021-09-28 01:29 UTC, kpango approved these changes
Your contribution to this project has been extremely valuable.
I believe in your decision and hope that your experience in this project will be useful to your future.

Thank you for the great job you did.

2021-09-28 01:31 UTC, kevindiu approved these changes
LGTM

2021-09-28 01:32 UTC, rinx commented
Thank you all :wave:

2021-09-29 10:06 UTC, kpango commented
I'll merge this PR tommorow.

2021-09-30 23:09 UTC, merged