Implement internal/net/grpc/credentials and health test
vdaas/vald pull request #1502
Opened 2021-12-01 06:27 UTC by kevindiu

Signed-off-by: kevindiu <kevindiujp@gmail.com>

### Description:

This PR implements internal/net/grpc/credentials and internal/net/grpc/health 

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.17.2
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.13.7

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [x] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [x] I have added tests and benchmarks to cover my changes.
- [x] I have ensured all new and existing tests passed.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2021-12-07 07:24 UTC, vankichi requested changes

2021-12-07 07:24 UTC, vankichi commented on internal/net/grpc/credentials/credentials_test.go
> +				c: &tls.Config{},
could you set the value of the `tls.Config{}` struct?

2021-12-07 08:41 UTC, kmrmt submitted a review, later dismissed

2021-12-07 08:52 UTC, kevindiu commented on internal/net/grpc/credentials/credentials_test.go
> +				c: &tls.Config{},
fixed, thank you!

2021-12-08 01:08 UTC, vankichi approved these changes

2021-12-08 02:57 UTC, kmrmt approved these changes

2021-12-08 04:46 UTC, kevindiu commented
/rebase
/approve

2021-12-08 04:51 UTC, merged