Add agent component overview document
vdaas/vald pull request #1544
Opened 2022-02-03 07:11 UTC by vankichi

Signed-off-by: vankichi <kyukawa315@gmail.com>

### Description:

I have created a document about the agent component overview.

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.17.5
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.13.8

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [x] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2022-02-14 00:52 UTC, kmrmt approved these changes

2022-02-14 06:16 UTC, kmrmt requested changes
I'm sorry if `assets/docs/overview/component/agent/ngt.png` has already been discussed, but I think I need to add `Upsert` to the list of operations.
(I don't know how to comment to binary file directly...)

2022-02-14 06:43 UTC, vankichi commented
@kmrmt 
> I'm sorry if `assets/docs/overview/component/agent/ngt.png` has already been discussed, but I think I need to add `Upsert` to the list of operations. (I don't know how to comment to binary file directly...)

This image applies to the features list, which I don't mention the `Upsert` in.
It is because a little bit complex comparing other functions.
If it should be there, I'll add it and update the image too.

2022-02-15 01:35 UTC, kmrmt approved these changes
@vankichi OK, I understand.

2022-02-16 02:00 UTC, kevindiu commented on docs/overview/component/agent.md
> +  - When the Vald Agent Pod reboots, the index structure is restored using external backup files.
```suggestion
  - When the Vald Agent Pod restart, the index structure is restored from the external backup files.
```

2022-02-16 02:20 UTC, vankichi commented on docs/overview/component/agent.md
> +  - Create a new NGT index structure in memory using vectors stored in the `vqueue` and the existing NGT index structure if it exists.
@kevindiu If NGT index structure already exists, the new NGT index consists of new insert vectors and it.

2022-02-16 07:14 UTC, vankichi commented on docs/overview/component/agent.md
> +You have to wait to complete CreateIndex and SaveIndex functions.
I already fixed by Grammarly suggestion

2022-02-16 07:46 UTC, vankichi commented on docs/overview/component/agent.md
> +- Store index data along to the user requests
sorry, I'm not sure about your question.
could you please show detail?

2022-02-17 02:15 UTC, kevindiu commented on docs/overview/component/agent.md
> +- Store index data along to the user requests
Sorry I mean there is no grammar of `along to the` in english, so i couldn't understand what this sentence means.

2022-02-17 02:20 UTC, kevindiu commented on docs/overview/component/agent.md
> +  - Create a new NGT index structure in memory using vectors stored in the `vqueue` and the existing NGT index structure if it exists.
I think it should be more clear.
```suggestion
  - Create a new NGT index structure in memory using vectors stored in the `vqueue` and store to the existing NGT index structure.
```

2022-02-17 02:23 UTC, vankichi commented on docs/overview/component/agent.md
> +  - Create a new NGT index structure in memory using vectors stored in the `vqueue` and the existing NGT index structure if it exists.
IMO, it is not correct because NGT index structure does not exist when the initial phase

2022-02-17 06:27 UTC, kevindiu approved these changes

2022-02-17 06:46 UTC, kmrmt approved these changes

2022-02-17 07:46 UTC, kpango approved these changes

2022-02-17 07:52 UTC, merged