fix go tool installation
vdaas/vald pull request #1649
Opened 2022-05-11 09:52 UTC by kmrmt

Signed-off-by: Kosuke Morimoto <ksk@vdaas.org>

### Description:

SSIA

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.18.1
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.14.3

### Types of changes:

- [X] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [X] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2022-05-12 02:45 UTC, kpango requested changes

2022-05-12 02:45 UTC, kpango commented on Makefile.d/test.mk
> +	go install github.com/mfridman/tparse@latest
```suggestion
	$(call go-get, github.com/mfridman/tparse)
```

2022-05-12 02:45 UTC, kpango commented on Makefile.d/test.mk
> +	go install github.com/cweill/gotests/gotests@latest
```suggestion
	$(call go-get, github.com/cweill/gotests/gotests)
```

2022-05-12 02:46 UTC, kpango commented
after suggestion commit.
could you please replace the Makefile function (go-get) name to go-install?

2022-05-13 03:50 UTC, hlts2 approved these changes
LGTM

2022-05-13 05:01 UTC, kpango commented on Makefile.d/functions.mk
> +define go-install
for this change you should also edit proto.mk

2022-05-13 07:07 UTC, kpango approved these changes
LGTM

2022-05-16 02:18 UTC, hlts2 approved these changes
LGTM

2022-05-16 02:21 UTC, merged