Remove unnecessary import path on pkg test
vdaas/vald pull request #1712
Opened 2022-06-23 07:42 UTC by kevindiu

Signed-off-by: kevindiu <kevindiujp@gmail.com>

### Description:

Same as title

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.18.3
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.14.6

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [x] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [x] I have ensured all new and existing tests passed.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2022-06-23 07:47 UTC, vankichi requested changes

2022-06-23 07:47 UTC, vankichi commented on pkg/agent/core/ngt/handler/grpc/insert_test.go
> +		}
`ok_1` -> `gok`
`ok_2` -> `wok`

2022-06-23 08:31 UTC, hlts2 approved these changes

2022-06-24 01:34 UTC, kpango approved these changes

2022-06-27 04:44 UTC, merged