[Experimental] [WIP] add QUIC support and use netpoll for more efficient network handling
vdaas/vald pull request #1771
Opened 2022-08-16 02:21 UTC by kpango

Signed-off-by: kpango <kpango@vdaas.org>

### Description:
Vald has been working on minimizing the overhead of the network by enhancing the libraries around each network, including gRPC.
Recently, the final specification of QUIC has been fixed, and Vald would like to verify the approach of gRPC over QUIC, since it will be in practical use soon.
This PR contains the code to verify gRPC over QUIC using quic-go from netpoll and other Network I/O blocking solutions.

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.16.6
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2024-10-28 22:23 UTC, kpango commented
@coderabbitai fullreview

2024-11-06 12:10 UTC, kmrmt approved these changes

2024-11-06 16:15 UTC, vankichi approved these changes
LGTM

2024-11-06 16:18 UTC, vankichi submitted a review, later dismissed
Sorry,  I found CI errors, please wait for merging to the main.

2024-11-07 10:38 UTC, kmrmt requested changes

2024-11-07 10:38 UTC, kmrmt commented on internal/client/v1/client/discoverer/discover.go
> +	if err != nil {
```suggestion
	if err == nil {
```

2024-11-07 12:54 UTC, kpango commented on internal/client/v1/client/discoverer/discover.go
> +	if err != nil {
```suggestion
	if err == nil && nbody != nil {
```

2024-11-07 13:12 UTC, kpango commented on internal/net/quic/listener.go
> +}
should we think about io.EOF?

2024-11-11 07:35 UTC, kmrmt submitted a review, later dismissed

2024-11-11 09:34 UTC, kmrmt submitted a review, later dismissed

2024-11-11 11:35 UTC, vankichi approved these changes

2024-11-12 01:02 UTC, kmrmt approved these changes

2024-11-13 00:27 UTC, kmrmt approved these changes

2024-11-13 02:16 UTC, vankichi approved these changes

2024-11-13 03:33 UTC, merged