[WIP] Add crds for continuous benchmark tools
vdaas/vald pull request #1779
Opened 2022-08-25 04:26 UTC by vankichi

Signed-off-by: vankichi <kyukawa315@gmail.com>

### Description:

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.18.3
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.14.7

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2022-09-01 02:22 UTC, kpango requested changes
Sorry I couldn't find struct which implements `k8s.io/apimachinery/pkg/runtime.Object`

2022-09-08 07:24 UTC, kpango commented on internal/k8s/benchmark/operator/operator.go
> +//+kubebuilder:rbac:groups=vald.vdaas.org.vald.vdaas.org,resources=valdbenchmarkoperators/finalizers,verbs=update
```suggestion
```

2022-09-08 07:25 UTC, kpango commented on internal/k8s/benchmark/job/job.go
> +//+kubebuilder:rbac:groups=vald.vdaas.org.vald.vdaas.org,resources=valdbenchmarkjobs/finalizers,verbs=update
```suggestion
```

2022-09-08 08:43 UTC, hlts2 commented on internal/k8s/benchmark/job/job.go
> +		opt(r)
Could you please add error handling for applying option? 🙏

2022-09-08 08:43 UTC, hlts2 commented on internal/k8s/benchmark/operator/operator.go
> +		opt(r)
Could you please add error handling for applying option? 🙏

2022-09-08 08:43 UTC, hlts2 commented on internal/k8s/benchmark/operator/types.go
> +	BenchmarkOperatorHealthy   = BenchmarkOperatorStatus("Healthy")
```suggestion
	BenchmarkOperatorNotReady BenchmarkOperatorStatus = "NotReady"
	BenchmarkOperatorAvailable   BenchmarkOperatorStatus = "Available"
	BenchmarkOperatorHealthy     BenchmarkOperatorStatus = "Healthy"
```

2022-09-08 08:54 UTC, kpango approved these changes

2022-09-12 01:27 UTC, hlts2 approved these changes

2022-09-12 02:23 UTC, kevindiu approved these changes

2022-09-12 04:50 UTC, merged