[WIP] Update unit test guideline for unimplemented test
vdaas/vald pull request #1983
Opened 2023-03-23 06:48 UTC by kevindiu

### Description:

### Related Issue:

### Versions:

- Go Version: 1.20.2
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 2.0.9

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### Special notes for your reviewer:

2023-03-28 01:53 UTC, kevindiu commented on docs/contributing/unit-test-guideline.md
> +2. When input is not `...interface{}` but `...[]int`, `...[]string` or etc.
```suggestion
1. When input is not `...interface{}` but `...[]int`, `...[]string` or etc.
```

2023-03-29 01:36 UTC, kevindiu commented on docs/contributing/unit-test-guideline.md
> +
```suggestion
```

2023-03-29 01:36 UTC, kevindiu commented on docs/contributing/unit-test-guideline.md
> +2. When input is not `...interface{}` but `...[]int`, `...[]string` or etc.
```suggestion
1. When input is not `...interface{}` but `...[]int`, `...[]string` or etc.
```

2023-03-30 08:51 UTC, kevindiu commented on CONTRIBUTING.md
> +    - [Branch naming convention](#branch-naming-convention)
```suggestion
- [Table of Contents](#table-of-contents)
- [Contributing Issue](#contributing-issue)
  - [Bug Report](#bug-report)
  - [Proposal](#proposal)
  - [Feature Request](#feature-request)
  - [Security Issue Report](#security-issue-report)
- [Contributing Source Code](#contributing-source-code)
  - [Before contributing source code](#before-contributing-source-code)
  - [How to contribute source code](#how-to-contribute-source-code)
  - [How to contribute test code](#how-to-contribute-test-code)
  - [Branch naming convention](#branch-naming-convention)
```

2023-03-30 08:52 UTC, kevindiu commented on CONTRIBUTING.md
> +- [Table of Contents](#table-of-contents)
```suggestion
```

2023-03-30 08:52 UTC, kevindiu commented on CONTRIBUTING.md
> +- [Table of Contents](#table-of-contents)
```suggestion
```

2023-04-03 01:44 UTC, kevindiu commented on CONTRIBUTING.md
> +However in Vald, we need some extra steps when making changes to test code.
```suggestion
However, in Vald, we need some extra steps when making changes to test code.
```

2023-04-03 01:44 UTC, kevindiu commented on CONTRIBUTING.md
> +Every unit test file should contains the placeholder in the file.
```suggestion
Every unit test file should contain the placeholder in the file.
```

2023-04-03 01:44 UTC, kevindiu commented on CONTRIBUTING.md
> +If all of the test functions are implemented, the placeholder will be placed on the bottom of the unit test file.
```suggestion
If all the test functions are implemented, the placeholder will be placed on the bottom of the unit test file.
```

2023-04-14 02:55 UTC, vankichi reviewed
You have to re-construct this chapter.
It seems to hard to understand what contributors should do when contributing tests.

This document requires the following:
1. How to contribute test code
    - not only a sentence. Please add all the steps when contributing test codes.
2. What is the structure of the test file

IMO, this PR does not satisfy all of the above yet and should be more systematic.

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +However, in Vald, we need some extra steps when making changes to test code.
```suggestion
But, there are some extra steps when making changes to the test code.
```

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +In Vald, the table-driven test functions of the unit test are generated by [gotests](https://github.com/cweill/gotests) using the `make gotests/gen` command.
```suggestion
Vald applies the table-driven test functions of the unit test generated by [gotests](https://github.com/cweill/gotests) using the `make gotests/gen` command.
```

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +We implemented our own [test template for gotests](https://github.com/vdaas/vald/tree/main/assets/test/templates) to generate the unit test functions, to provide extra flexibility and functionality f
```suggestion
Vald uses its own [test template for gotests](https://github.com/vdaas/vald/tree/main/assets/test/templates) to generate the unit test functions, to provide extra flexibility and functionality for the unit test, such as [goleak](https://github.com/uber-go/goleak) support.
```

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +However, when we update our test template, the generated unit test functions will not be updated accordingly.
```suggestion
However, when the test template is updated, the generated unit test functions will not be updated accordingly.
```

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +To overcome this, we implemented a placeholder `// NOT IMPLEMENTED BELOW` to indicate whether the test functions are implemented or not. The unit test functions above the placeholder are implemented,
```suggestion
To overcome this, each test file has a placeholder `// NOT IMPLEMENTED BELOW` to indicate whether the test functions are implemented.
The unit test functions above the placeholder are implemented, and the functions below still need to be implemented.
If all the test functions are implemented, the placeholder will be placed at the bottom of the unit test file.
```

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +When the test template is updated, if the unit test function is implemented already, we cannot do anything about it. But for unit test functions that are not implemented yet, we can re-generate them
```suggestion
The implemented unit test is not updated even when the test template is updated.
On the other hand, we have to re-generate unimplemented tests by using the latest test template.
```

2023-04-14 02:55 UTC, vankichi commented on CONTRIBUTING.md
> +If all the test functions are implemented, the placeholder will be placed on the bottom of the unit test file.
```suggestion
```

2023-04-17 07:26 UTC, vankichi commented on CONTRIBUTING.md
> +For the implemented unit test, we cannot deal with it with the `make gotests/gen` command.
```suggestion
<div class="notice">
This implementation structure is generated by the <code class="bash" data-lang="bash>make gotests/gen</code> command for all unit test files by applying the custom unit test template using <a href="https://github.com/cweill/gotests">gotests</a>.
<br>
When the test template is updated, the generated unit test functions will not be updated accordingly, so we need this unit test structure to help us regenerate the implementation with the latest template.
For the implemented unit test, we cannot deal with it by executing  <code class="bash" data-lang="bash>make gotests/gen</code> command.
But we don't have to update implemented test soon.
</div>
```

2023-04-18 01:37 UTC, vankichi approved these changes

2023-04-18 01:39 UTC, vankichi requested changes

2023-04-18 01:39 UTC, vankichi commented on CONTRIBUTING.md
> +This implementation structure is generated by the <code class="bash" data-lang="bash>make gotests/gen</code> command for all unit test files by applying the custom unit test template using <a href="h
```suggestion
This implementation structure is generated by the <code class="bash" data-lang="bash">make gotests/gen</code> command for all unit test files by applying the custom unit test template using <a href="https://github.com/cweill/gotests">gotests</a>.
```

2023-04-18 01:39 UTC, vankichi commented on CONTRIBUTING.md
> +For the implemented unit test, we cannot deal with it by executing  <code class="bash" data-lang="bash>make gotests/gen</code> command.
```suggestion
For the implemented unit test, we cannot deal with it by executing  <code class="bash" data-lang="bash">make gotests/gen</code> command.
```

2023-04-18 06:01 UTC, vankichi approved these changes

2023-04-18 07:48 UTC, datelier approved these changes

2023-04-18 07:51 UTC, merged