Implement generic tests
vdaas/vald pull request #2008
Opened 2023-04-13 08:32 UTC by kevindiu

### Description:

### Related Issue:

### Versions:

- Go Version: 1.20.3
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 2.0.9

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### Special notes for your reviewer:

2023-04-13 08:35 UTC, kevindiu commented on internal/test/mock/server_stream.go
> -	"github.com/vdaas/vald/internal/net/grpc"
to fix cycle import

2023-04-13 08:41 UTC, kevindiu commented
/gen-test
/format

2023-04-14 04:17 UTC, kevindiu commented on internal/slices/slices_test.go
> +	"errors"
```suggestion
	"internal/errors"
```

2023-04-14 09:12 UTC, kevindiu commented
/gen-test
/format

2023-04-17 01:17 UTC, kevindiu commented
/gen-test

2023-04-17 03:34 UTC, kevindiu commented
/gen-test

2023-04-18 06:10 UTC, vankichi requested changes

2023-04-18 06:10 UTC, vankichi commented on internal/net/grpc/stream_test.go
> +
```suggestion
```

2023-04-18 06:10 UTC, vankichi commented on internal/net/grpc/stream_test.go
> +
```suggestion
```

2023-04-18 06:10 UTC, vankichi commented on internal/net/grpc/stream_test.go
> +		defaultConcurrency = 10
```suggestion
		name        = "vald-agent-ngt-1" // agent name
		f32VecDim   = 3                  // float32 vector dimension
		ip          = "localhost"        // ip address
		concurrency = 10
```

2023-04-18 07:03 UTC, kevindiu commented on internal/net/grpc/stream_test.go
> +		defaultConcurrency = 10
fixed

2023-04-18 08:09 UTC, hlts2 approved these changes
LGTM

2023-04-18 15:35 UTC, vankichi approved these changes
LGTM

2023-04-19 02:30 UTC, merged