Update docs: search API and client API config
vdaas/vald pull request #2081
Opened 2023-06-19 08:53 UTC by vankichi

### Description:

SSIA

### Related Issue:

### Versions:

- Go Version: 1.20.3
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 2.0.11

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### Special notes for your reviewer:

2023-06-20 02:17 UTC, kpango requested changes

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/api/search.md
> +      aggregation_algorithm = 9;
```suggestion
      uint32 min_num = 8;
      AggregationAlgorithm aggregation_algorithm = 9;
```

2023-06-20 02:17 UTC, kpango commented on docs/user-guides/client-api-config.md
> +                        AggregationAlgorithm: 4,
```suggestion
                        AggregationAlgorithm: payload.Search_PairingHeap,
```

2023-06-20 08:14 UTC, kpango approved these changes
LGTM

2023-06-22 07:22 UTC, datelier approved these changes

2023-06-22 07:24 UTC, merged