[WIP] Add svc discoverer for readreplica svc
vdaas/vald pull request #2263
Opened 2023-12-07 05:58 UTC by ykadowak

### Description:

### Related Issue:

### Versions:

- Go Version: 1.21.5
- Docker Version: 20.10.8
- Kubernetes Version: v1.28.4
- NGT Version: 2.1.5

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### Special notes for your reviewer:

2023-12-11 09:00 UTC, vankichi commented
IMO, it would be better to change the path from `internal/k8s/readreplica/svc` to `internal/k8s/svc`, because it can be used for any methods not only for readReplica.

2023-12-11 09:08 UTC, ykadowak commented
> IMO, it would be better to change the path from `internal/k8s/readreplica/svc` to `internal/k8s/svc`, because it can be used for any method not only for readReplica.

I was thinking of that but this controller has to know `readreplica` specific things like `replica id` so it cannot be used generally.

2023-12-11 09:13 UTC, vankichi requested changes

2023-12-11 09:13 UTC, vankichi commented on internal/k8s/readreplica/svc/svc.go
> +			return reconcile.Result{}, fmt.Errorf("no valid label is put in the svc")
```suggestion
			return reconcile.Result{}, errors.New("no valid label is put in the svc")
```
If you do not need to format, `errors.New()` is better for performance.

2023-12-11 09:26 UTC, vankichi commented
> > IMO, it would be better to change the path from `internal/k8s/readreplica/svc` to `internal/k8s/svc`, because it can be used for any method not only for readReplica.
> 
> I was thinking of that but this controller has to know `readreplica` specific things like `replica id` so it cannot be used generally.

Hmm...
In the current implementation, a specific `replica id` is used for checking whether labels have replica key id, so how about changing the variable name in the struct from `keyId string` to `labels []string` and changing checking logic?
It is a just idea, and I'm wondering which is best, so I would like to hear your and other members' opinions.

2023-12-12 07:23 UTC, ykadowak commented
@vankichi 
Moved `internal/k8s/readreplica/svc` to `internal/k8s/svc` as we discussed by passing `corev1.Service` to `onReconcile`.
[2725af5](https://github.com/vdaas/vald/pull/2263/commits/2725af5d3133bc8f0b0373864dc79d59bce64065)

2023-12-12 15:37 UTC, vankichi approved these changes
Thanks! LGTM

2023-12-14 06:35 UTC, vankichi reviewed
Overall LGTM.
I would appreciate it if you added a comment for each Global value/function that you implemented.
e.g.
    - `internal/k8s/service/...` files 
    - `pkg` files

2023-12-18 02:22 UTC, vankichi approved these changes
LGTM

2023-12-18 02:27 UTC, kpango approved these changes
LGTM

2023-12-18 02:27 UTC, merged