[Coding guideline] Add implementation and grouping section
vdaas/vald pull request #641
Opened 2020-08-25 06:53 UTC by kevindiu

### Description:

This PR update the coding guideline and create 2 new section to cover the following things:

- add example of implementation for functional option
- grouping type declaration 
- order of declaration

Please refer to this task ticket for this PR

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.14.4
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.0

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2020-08-25 07:03 UTC, hlts2 requested changes

2020-08-25 07:03 UTC, hlts2 commented on docs/contributing/coding-style.md
> +This section includes some examples of general implementation which is widely used in Vald. The implementation may differ base on your use case.
```suggestion
This section includes some examples of general implementation which is widely used in Vald. The implementation may differ based on your use case.
```

2020-08-25 07:03 UTC, hlts2 commented on docs/contributing/coding-style.md
> +        c.version = version
```suggestion
       if len(version) != 0 {
              c.version = version       
       }
```

2020-08-25 07:45 UTC, hlts2 commented on docs/contributing/coding-style.md
> +func WithTimeout(dur string) Option {
I want the indent to look nicer. :pray:

2020-08-25 07:52 UTC, kevindiu commented on docs/contributing/coding-style.md
> +func WithTimeout(dur string) Option {
what do you mean?

2020-08-25 08:05 UTC, kevindiu commented on docs/contributing/coding-style.md
> +func WithTimeout(dur string) Option {
fixed. please check :)

2020-08-25 08:54 UTC, hlts2 approved these changes
LGTM

2020-08-25 09:26 UTC, vankichi commented on docs/contributing/coding-style.md
> +Put the higher priority or frequently used declaration on the top of other declaration. It makes Vald easier to read and search the target source code in Vald.
```suggestion
Put the higher priority or frequently used declaration on the top of other declaration.
It makes Vald easier to read and search the target source code in Vald.
```

2020-08-25 09:26 UTC, vankichi commented on docs/contributing/coding-style.md
> +For example, the interface declaration should have higher priority then struct or function declaration, hence it should be put above other declaration.
```suggestion
For example, the interface declaration should have higher priority than struct or function declaration, hence it should be put above other declaration.
```

2020-08-25 09:26 UTC, vankichi commented on docs/contributing/coding-style.md
> +Group similar definitions such as struct or interface declaration. We should not group interface and struct declaration in the same block, for example:
```suggestion
Group similar definitions such as struct or interface declaration.
We should not group interface and struct declaration in the same block, for example:
```

2020-08-25 09:26 UTC, vankichi commented on docs/contributing/coding-style.md
> +This section includes some examples of general implementation which is widely used in Vald. The implementation may differ based on your use case.
```suggestion
This section includes some examples of general implementation which is popular in Vald.
The implementation may differ from your use case.
```

2020-08-25 09:26 UTC, vankichi commented on docs/contributing/coding-style.md
> +In Vald, the functional option pattern is widely used in Vald. You can refer to [this section](#Struct-initialization) for more details of the use case of this pattern.
```suggestion
In Vald, the functional option pattern is widely used in Vald.
You can refer to [this section](#Struct-initialization) for more details of the use case of this pattern.
```

2020-08-25 09:26 UTC, vankichi commented on docs/contributing/coding-style.md
> +We suggest the following implementation to set the value to the target.
```suggestion
We strongly suggest the following implementation to set the value to the target.
```

2020-08-26 00:50 UTC, kevindiu commented on docs/contributing/coding-style.md
> +We suggest the following implementation to set the value to the target.
I changed it to 
```
We strongly recommend the following implementation to set the value using functional option.
```

2020-08-26 02:32 UTC, hlts2 approved these changes
LGTM

2020-08-26 02:33 UTC, hlts2 requested changes

2020-08-26 02:33 UTC, hlts2 commented on docs/contributing/coding-style.md
> +We recommend using the following implementation to parse the time string and set the time to the target struct.
```suggestion
We recommend the following implementation to parse the time string and set the time to the target struct.
```

2020-08-26 07:34 UTC, hlts2 approved these changes
LGTMed

2020-08-26 08:00 UTC, vankichi approved these changes
LGTM

2020-08-26 08:14 UTC, vankichi approved these changes

2020-08-26 09:22 UTC, rinx approved these changes

2020-08-27 02:09 UTC, hlts2 submitted a review, later dismissed
LGTM

2020-08-27 02:22 UTC, vankichi commented on docs/contributing/coding-style.md
>  if err != nil {
Why you don't use side-by-side style here?

2020-08-27 02:35 UTC, hlts2 approved these changes
sorry I overlooked [this]()
LGTMed

2020-08-27 02:58 UTC, vankichi commented on docs/contributing/coding-style.md
>  ```
opposite

2020-08-27 03:05 UTC, kpango commented
/rebase
/format

2020-08-27 03:12 UTC, kpango approved these changes
LGTM

2020-08-27 03:13 UTC, merged