Test/internal/nosql/cassandra test
vdaas/vald pull request #809
Opened 2020-10-30 07:30 UTC by kevindiu

### Description:

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.15.2
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.1

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2020-10-30 07:31 UTC, kevindiu commented
/rebase

2020-11-04 07:06 UTC, hlts2 requested changes

2020-11-04 07:06 UTC, hlts2 commented on internal/db/nosql/cassandra/cassandra_test.go
> +					Eq("col"),
should we increase the number of `Cmp `  ?

2020-11-04 07:06 UTC, hlts2 commented on internal/db/nosql/cassandra/cassandra_test.go
> +					columns: []string{"col"},
same 
https://github.com/vdaas/vald/pull/809/files#r517132827

2020-11-04 07:06 UTC, hlts2 commented on internal/db/nosql/cassandra/cassandra_test.go
> +				names: []string{"n"},
same
https://github.com/vdaas/vald/pull/809/files#r517132827

2020-11-04 07:08 UTC, hlts2 commented on internal/db/nosql/cassandra/cassandra_test.go
> +			want: want{},
could you please check the session object if error or not with checkFunc?

2020-11-04 09:23 UTC, hlts2 approved these changes
LGTM

2020-11-10 07:23 UTC, vankichi approved these changes

2020-11-10 07:24 UTC, vankichi commented
/rebase
/format
/approve

2020-11-10 10:04 UTC, vankichi commented
/rebase
/format
/approve

2020-11-10 10:06 UTC, vankichi commented
/format
/approve

2020-11-10 10:22 UTC, merged