Test/internal/errors/blob test
vdaas/vald pull request #888
Opened 2020-12-16 05:36 UTC by kevindiu

### Description:
This PR implements internal/errors/blob test

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.15.2
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.1

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2020-12-16 05:36 UTC, kevindiu commented
/rebase

2020-12-17 03:25 UTC, hlts2 requested changes

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +				name: "unwrap returns the unwrapped error",
```suggestion
				name: "returns the unwrapped error",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +				name: "unwrap returns the unwrapped error",
```suggestion
				name: "returns the unwrapped error",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +			name: "error return error string",
```suggestion
			name: "returns error string",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +			name: "return false when the error is not ErrBlobNoSuchKey",
```suggestion
			name: "returns false when the error is not ErrBlobNoSuchKey",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +			name: "return true when the error is ErrBlobNoSuchKey",
```suggestion
			name: "returns true when the error is ErrBlobNoSuchKey",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +			name: "return true when the error is ErrBlobNoSuchBucket",
```suggestion
			name: "returns true when the error is ErrBlobNoSuchBucket",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +			name: "return false when the error is not ErrBlobNoSuchBucket",
```suggestion
			name: "returns false when the error is not ErrBlobNoSuchBucket",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +			name: "error return error string",
```suggestion
			name: "returns error string",
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob.go
> +// Error return the string representation of the internal error.
```suggestion
// Error returns the string representation of the internal error.
```

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +		},
Should we add a test case when error is nil?

2020-12-17 03:25 UTC, hlts2 commented on internal/errors/blob_test.go
> +		},
Should we add test case when err is nil ?

2020-12-18 02:41 UTC, vankichi commented on internal/errors/blob_test.go
> +				err: New("anothererr"),
```suggestion
				err: &ErrBlobNoSuchKey{New("no such key err")}
```
how about it?
i think it'd be more meaningful 🤔

2020-12-18 02:41 UTC, vankichi commented on internal/errors/blob_test.go
> +				err: New("anothererr"),
```suggestion
				err: &ErrBlobNoSuchBucket{New("no such bucket err")},
```
same 🤔

2020-12-18 02:41 UTC, vankichi commented on internal/errors/blob_test.go
> +			name: "returns the unwrapped nil error",
```suggestion
			name: "returns nil when get the unwrapped nil error",
```

2020-12-18 02:41 UTC, vankichi commented on internal/errors/blob_test.go
> +			name: "returns the unwrapped nil error",
```suggestion
			name: "returns nil when get the unwrapped nil error",
```

2020-12-21 03:06 UTC, kevindiu commented on internal/errors/blob_test.go
> +			name: "returns the unwrapped nil error",
I think it is more correct.
```suggestion
			name: "returns nil when getting the unwrapped nil error",
```

2020-12-21 03:06 UTC, kevindiu commented on internal/errors/blob_test.go
> +			name: "returns the unwrapped nil error",
```suggestion
			name: "returns nil when getting the unwrapped nil error",
```

2020-12-21 03:07 UTC, kevindiu commented
/rebase

2020-12-21 03:11 UTC, hlts2 approved these changes
LGTM

2020-12-22 02:07 UTC, vankichi commented on internal/errors/blob_test.go
> +				err: New("err"),
```suggestion
				err: New("err: no such bucket"),
```

2020-12-22 02:07 UTC, vankichi commented on internal/errors/blob_test.go
> +				err: &ErrBlobNoSuchKey{New("nosuchkeyerr")},
```suggestion
				err: &ErrBlobNoSuchKey{New("no such key err")},
```

2020-12-22 02:07 UTC, vankichi commented on internal/errors/blob_test.go
> +				err: &ErrBlobNoSuchBucket{New("nosuchbucketerr")},
```suggestion
				err: &ErrBlobNoSuchBucket{New("no such bucket err")},
```

2020-12-22 02:28 UTC, kevindiu commented on internal/errors/blob_test.go
> +				want: "err",
```suggestion
				want: "err: no such bucket",
```

2020-12-22 04:29 UTC, kevindiu commented
/rebase

2020-12-22 04:43 UTC, hlts2 approved these changes
LGTM

2020-12-22 04:56 UTC, vankichi approved these changes
LGTM

2020-12-22 04:56 UTC, vankichi commented
/rebase
/format
/approve

2020-12-22 06:03 UTC, merged