Add test case for internal/errors/ngt.go
vdaas/vald pull request #936
Opened 2021-01-20 05:39 UTC by hlts2

Signed-off-by: hlts2 <hiroto.funakoshi.hiroto@gmail.com>

### Description:

I added the test cases for internal/errors/ngt.go and comments.

~~grammar check passed~~

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.15.6
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2021-01-20 05:43 UTC, hlts2 commented on internal/errors/ngt.go
> +	// ErrDimensionLimitExceed represents a function to generate an error that the supported dimension limit exceded.
```suggestion
	// ErrDimensionLimitExceed represents a function to generate an error that the supported dimension limit exceeded.
```

2021-01-20 05:43 UTC, hlts2 commented on internal/errors/ngt.go
> +	// ErrUncommittedIndexExists represents a function to generate an error that the uncommitted indexes exists.
```suggestion
	// ErrUncommittedIndexExists represents a function to generate an error that the uncommitted indexes exist.
```

2021-01-25 05:10 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrDimensionLimitExceed error when current and limit are the minimum value of math.Int64",
```suggestion
			name: "return ErrDimensionLimitExceed error when current and limit are the minimum value of int",
```

2021-01-25 05:10 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrDimensionLimitExceed error when current and limit are the maximum value of math.Int64",
```suggestion
			name: "return ErrDimensionLimitExceed error when current and limit are the maximum value of int",
```

2021-01-25 05:10 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrFailedToSetCreationEdgeSize error when err is ngt error",
```suggestion
			name: "return ErrFailedToSetCreationEdgeSize error when err is nil",
```

2021-01-25 05:10 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrUUIDNotFound error when id is maximum value of math.Uint32",
```suggestion
			name: "return ErrUUIDNotFound error when id is the maximum value of uint32",
```

2021-01-25 05:10 UTC, hlts2 commented on internal/errors/ngt_test.go
> +				name: "return ErrUncommittedIndexExists error when num is the maximum value of math.Uint64",
```suggestion
				name: "return ErrUncommittedIndexExists error when num is the maximum value of uint64",
```

2021-01-25 05:10 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrUUIDAlreadyExists error when uuid is '550e8400-e29b-41d4' and oid is maximum value of math.Uint64",
```suggestion
			name: "return ErrUUIDAlreadyExists error when uuid is '550e8400-e29b-41d4' and oid is the maximum value of uint64",
```

2021-01-27 03:05 UTC, vankichi requested changes
please check these suggestion

2021-01-27 11:28 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrUnsupportedDistanceType error",
```suggestion
			name: "return an ErrUnsupportedDistanceType error",
```

2021-01-27 11:28 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return wrapped ErrFailedToSetDimension error when err is ngt error",
```suggestion
			name: "return a wrapped ErrFailedToSetDimension error when err is ngt error",
```

2021-01-27 11:28 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrFailedToSetDimension error when err is nil",
```suggestion
			name: "return an ErrFailedToSetDimension error when err is nil",
```

2021-01-27 11:28 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrUncommittedIndexNotFound error",
```suggestion
			name: "return an ErrUncommittedIndexNotFound error",
```

2021-01-27 11:28 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return ErrCAPINotImplemented error",
```suggestion
			name: "return an ErrCAPINotImplemented error",
```

2021-01-27 11:30 UTC, hlts2 commented on internal/errors/ngt_test.go
> +			name: "return an ErrFailedToSetObjectType error when err is nil and t is Float",
```suggestion
			name: "return an ErrFailedToSetObjectType error when err is nil and t is Int",
```

2021-01-29 02:40 UTC, vankichi approved these changes

2021-02-01 09:29 UTC, kevindiu submitted a review, later dismissed
LGTM

2021-02-01 09:33 UTC, kevindiu commented
/format
/rebase
/approve

2021-02-01 09:44 UTC, kevindiu commented
/rebase
/format
/approve

2021-02-01 09:51 UTC, kevindiu commented
/rebase
/format
/approve

2021-02-01 22:44 UTC, kevindiu commented
/rebase
/format
/approve

2021-02-02 02:07 UTC, kevindiu commented
/rebase
/format
/approve

2021-02-02 02:12 UTC, merged