V1.0.0 Stable Release
vdaas/vald pull request #963
Opened 2021-01-29 06:21 UTC by kpango

Signed-off-by: kpango <kpango@vdaas.org>

### Description:
#### V1.0.0 Release
this version includes many feature.

#### New Feature
1. The Vald-Gateway has been divided into four Gateways (LB, Meta, Backup and Filter).
2. API returns correct status and detailed error message.
3. StreamAPI returns detailed error status payload for each chunked requests were failed
4. improved vald network component performance
5. improved observability for each function
6. structured helm chart for managers and gateways
7. Filter gateway is now GA, Users can issue requests with extracted feature vectors inline for search/insert/update/upsert requests.
8. gRPC proto files are now Versioned for future changes
9. users can access Vald agent using vald api client.
10. internal/client packages are now GA, each vald component can use it for effective connection management and easily to send reqest.

#### Breaking Changes
1. API interface changed.
2. Helm Chart changed.
3. Vald-gateway will be deprecated in a future version.
4. k8s controller-runtime updated internal/k8s controller is now new context interface
5. Vald Agent now uses same API definition as vald v1 gateway interface.

#### 

### Related Issue:

### How Has This Been Tested?:

### Environment:

- Go Version: 1.15.7
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.13.1

### Types of changes:

- [ ] Bug fix [type/bug]
- [x] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [x] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

2021-01-29 06:23 UTC, kpango commented
/changelog

2021-01-29 06:59 UTC, kevindiu approved these changes
LGTM.
Happy birthday 👏

2021-01-29 06:59 UTC, hlts2 approved these changes
LGTM 👍

2021-01-29 07:08 UTC, rinx commented
I'm not sure but the several dependencies are updated in this PR. Is that okay?

2021-01-29 07:15 UTC, kpango commented
@rinx I think it's okay, because each dependencies are small update and I check this build on my local cluster it works fine.

If you interest please check below each one looks not breaking changes and just update small things.
https://github.com/gocql/gocql/compare/9e3bb6cbd881...14aa133462a3
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/compare/v0.13.4...v0.13.5
https://github.com/aws/aws-sdk-go/releases/tag/v1.37.0
https://github.com/lucasb-eyer/go-colorful/compare/v1.0.3...v1.2.0

2021-01-29 07:18 UTC, rinx approved these changes

2021-01-29 07:32 UTC, kpango commented
@rinx Recently kubectl command may not find the resource even if you run a watch request immediately after deployment!
So I recently added the sleep command for scylla and it works.

example
https://github.com/vdaas/vald/blob/master/Makefile.d/k8s.mk#L261
https://github.com/vdaas/vald/blob/master/Makefile.d/k8s.mk#L282

2021-01-29 07:34 UTC, rinx commented
yes, please.

2021-01-29 07:34 UTC, kpango commented
okay, I'll do it.

2021-01-29 07:36 UTC, rinx commented
Maybe E2E tests for deploying with Cassandra requires changes like this.
https://github.com/vdaas/vald/pull/899/commits/442e82d12c67fe6ed077510412c1cbdaf83c902f

2021-01-29 07:42 UTC, kpango commented
@rinx thank you for your attention, I updated `.github/helm/values/values-scylla.yaml`

2021-02-01 08:00 UTC, rinx requested changes

2021-02-01 08:00 UTC, rinx commented on .github/workflows/e2e-deploy.yml
> +          K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 make k8s/external/redis/deploy
```suggestion
          make K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 k8s/external/mysql/deploy
          make K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 k8s/external/redis/deploy
```

2021-02-01 08:00 UTC, rinx commented on .github/workflows/e2e-deploy.yml
> +          K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 make k8s/external/scylla/deploy
```suggestion
          make K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 k8s/external/scylla/deploy
```

2021-02-01 08:00 UTC, rinx commented on .github/workflows/e2e-deploy.yml
> +          K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 make k8s/external/minio/deploy
```suggestion
          make K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 k8s/external/minio/deploy
```

2021-02-01 08:00 UTC, rinx commented on Makefile.d/k8s.mk
> +	sleep ${K8S_SLEEP_DURATION_FOR_WAIT_COMMAND}
```suggestion
	sleep $(K8S_SLEEP_DURATION_FOR_WAIT_COMMAND)
```

2021-02-01 08:00 UTC, rinx commented on Makefile.d/k8s.mk
> +	sleep ${K8S_SLEEP_DURATION_FOR_WAIT_COMMAND}
```suggestion
	sleep $(K8S_SLEEP_DURATION_FOR_WAIT_COMMAND)
```

2021-02-01 08:00 UTC, rinx commented on Makefile.d/k8s.mk
> +	sleep ${K8S_SLEEP_DURATION_FOR_WAIT_COMMAND}
```suggestion
	sleep $(K8S_SLEEP_DURATION_FOR_WAIT_COMMAND)
```

2021-02-01 08:00 UTC, rinx commented on Makefile.d/k8s.mk
> +	sleep ${K8S_SLEEP_DURATION_FOR_WAIT_COMMAND}
```suggestion
	sleep $(K8S_SLEEP_DURATION_FOR_WAIT_COMMAND)
```

2021-02-01 08:00 UTC, rinx commented on Makefile.d/k8s.mk
> +	sleep ${K8S_SLEEP_DURATION_FOR_WAIT_COMMAND}
```suggestion
	sleep $(K8S_SLEEP_DURATION_FOR_WAIT_COMMAND)
```

2021-02-01 08:00 UTC, rinx commented on Makefile.d/k8s.mk
> +	sleep ${K8S_SLEEP_DURATION_FOR_WAIT_COMMAND}
```suggestion
	sleep $(K8S_SLEEP_DURATION_FOR_WAIT_COMMAND)
```

2021-02-01 08:00 UTC, kpango commented on .github/workflows/e2e-deploy.yml
> +          K8S_SLEEP_DURATION_FOR_WAIT_COMMAND=10 make k8s/external/redis/deploy
I'll work on it after bug fix/

2021-02-02 05:24 UTC, merged